version: '2'

services:

    mysql:
        image: mysql
        restart: always
        env_file:
            - variables.env
        # volumes:
        #     - ./data/mysql:/docker-entrypoint-initdb.d
        
    wordpress:
        depends_on:
            - mysql
        image: wordpress
        ports:
            - "80:80"
        restart: always
        working_dir: /var/www/html     